service: ondeck-powerlifting-api

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DATABASE_NAME: ${DATABASE_NAME}
    DATABASE_USER: ${DATABASE_USER}
    DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    DATABASE_HOST: ${DATABASE_HOST}
    DATABASE_PORT: ${DATABASE_PORT}

functions:
  hello:
    handler: src/handler.helloFetch
    events:
      - http:
          path: hello
          method: get
  helloCreate:
    handler: src/handler.helloCreate
    events:
      - http:
          path: hello/{value}
          method: get
          request: 
            parameters: 
              paths: 
                value: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  webpack:
    includeModules:
      forceInclude:
        - pg
        - pg-hstore
