service: ondeck-powerlifting-api

provider:
  name: aws
  region: us-east-1
  stage: ${env:DEPLOY_STAGE}
  runtime: nodejs12.x
  environment:
    DEPLOY_STAGE: ${env:DEPLOY_STAGE}
    DATABASE_NAME: ${env:DATABASE_NAME}
    DATABASE_USER: ${env:DATABASE_USER}
    DATABASE_PASSWORD: ${env:DATABASE_PASSWORD}
    DATABASE_HOST: ${env:DATABASE_HOST}
    DATABASE_PORT: ${env:DATABASE_PORT}

functions:
  app:
    handler: src/handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'


plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  webpack:
    includeModules:
      forceInclude:
        - pg
        - pg-hstore
